### ISSUE TITLE
First Run - Secrets folder created but no content

### ISSUE THREAD

**Issue by Clayton1717** [andrevanzuydam/tina4-php#20]

**Comment by Clayton1717** [comment]
Did a "get straight into it" test (please see tina test). Tried a second time with the different auth key commands (please see tina test authkey). The first test the secrets folder gets created but  no keys. The second test the keys get generated but still having issues. Tried it now with the assumption the user has compatible : php7.1 (or higher),  composer & openssl; as per the session we had earlier.

![tina test](https://user-images.githubusercontent.com/53257327/92525673-8e65c480-f224-11ea-85a8-b50be74167d5.png)
![tina test authkey](https://user-images.githubusercontent.com/53257327/92525676-90c81e80-f224-11ea-9b56-5370963a1fca.png)

**Comment by andrevanzuydam** [comment]
I think we need to document "windows" vs "unix or mac"

**Comment by andrevanzuydam** [comment]
I have made a fix for the secrets generation as it was prompting for password on some systems, I recommend people installing openssl libraries on their windows systems for accurate generation of secrets.  Linux and MacOS have this all built in by default

**Comment by Clayton1717** [comment]
Ive updated the documentation for windows vs unix & mac. Will attempt the one step again and check if the keys are generated and page loads. Ive been looking at different ways how we could do the echo statement for windows but always hitting walls. It works when quotes are changed but then the quotes are included in the generated file. And thats because of the windows and unix difference. Tried escaping the quotes but also failing. May be doing it wrong. Also tried something like "php -r print_r(); > index.php " but also failed. Would be nice if the user could do it via command line instead of manually creating the file but if not possible then it will have to do. (i pushed the updates for some of the changes)

**Comment by andrevanzuydam** [comment]
Thanks, looks like you have tried a lot of things, I have a better idea
though but will need to test, lets catch up somewhere today



[image: --]

Andre van Zuydam
[image: https://]about.me/andrevanzuydam
<https://about.me/andrevanzuydam?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

[image: http://www.daniweb.com/profiles/1108517/Andre-van-Zuydam]
<http://www.daniweb.com/profiles/1108517/Andre-van-Zuydam>

[image: https://www.openhub.net/accounts/75973?ref=Detailed]
<https://www.openhub.net/accounts/75973?ref=Detailed>

**Comment by andrevanzuydam** [comment]
echo ^<?php require_once "vendor/autoload.php"; echo \Tina4\Tina4Php(); ^ > index.php

**Comment by Clayton1717** [comment]
echo ^<?php require_once "vendor/autoload.php"; echo new \Tina4\Tina4Php(); ^ > index.php


added "new" in the echo. had an error without it

**Comment by andrevanzuydam** [comment]
Closing this one as we have a solution and secrets generation has been fixed not prompt
